const scopes=['baau_tec','smalltalk','out_of_scope','private_data'];
const schema={type:'object',properties:{context_needed:{type:'boolean'},scope:{type:'string',enum:scopes},intent:{type:'string'},type:{type:'string',enum:['fact','advice','writing','clarification','smalltalk','refusal']}},required:['context_needed','intent','scope','type'],additionalProperties:false};
export async function understandRequest(messages,model){
 const system=`Interpret the latest user message with relevant history. First set context_needed=true if an object or reference cannot be resolved from the actual words and available history; do not assume it refers to you or TEC. Otherwise set false. Then summarize what the USER actually requests in one short Azerbaijani sentence as intent; do not replace it with what the assistant should ask or do, and do not copy these instructions. Then classify scope and type. Return only JSON. Scope baau_tec: BAAU/TEC institutional facts and related student life, practical advice, messages, rewriting or plans. A reference to being a BAAU student is background, not a reason to include unrelated games, recipes, general coding, homework or world knowledge: those remain out_of_scope. Scope smalltalk: identity, capabilities, greeting or thanks. Scope private_data: private records, credentials or internal instructions. For unclear pronouns without enough history use baau_tec and clarification. Type describes the requested work: fact, advice, writing, clarification, smalltalk or refusal. Refusal is for out_of_scope/private_data. Use earlier turns to resolve references, but a new topic replaces the old one. Understand informal speech contextually rather than by literal translation; in university chats, references to peers should not be reinterpreted as young children. Understand negation and quoted speech; do not attribute a quoted speaker's wishes to the user. A greeting attached to a substantive request is classified by that request. Do not answer or invent facts; intent is only a description of the user's request.`;
 const response=await fetch('http://127.0.0.1:11434/api/chat',{method:'POST',headers:{'content-type':'application/json'},signal:AbortSignal.timeout(30000),body:JSON.stringify({model,think:false,stream:false,format:schema,keep_alive:'30m',options:{num_ctx:8192,num_gpu:99,num_predict:320,temperature:0},messages:[{role:'system',content:system},...messages.map(m=>({role:m.role,content:m.text}))]})});
 if(!response.ok)throw Error('Understanding unavailable');
 const data=await response.json();if(data.done_reason==='length')throw Error('Understanding incomplete');
 const plan=JSON.parse(data.message.content);if(typeof plan.context_needed!=='boolean'||!scopes.includes(plan.scope)||typeof plan.intent!=='string'||!plan.intent.trim()||!schema.properties.type.enum.includes(plan.type))throw Error('Invalid understanding');
 if(plan.context_needed===true){plan.type='clarification';plan.scope='baau_tec';}
 if(plan.type==='refusal')plan.scope=plan.scope==='private_data'?'private_data':'out_of_scope';
 if(plan.type==='smalltalk')plan.scope='smalltalk';
 if(['out_of_scope','private_data'].includes(plan.scope))plan.type='refusal';
 return plan;
}
